version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
